title: Bruno Rijsman's Quantum Resource List
description: A curated list of introductory books, papers, courses, and other online resources related to Quantum Networking, Quantum Key Distribution, and Quantum Computing.
google_analytics: 269357015
theme: jekyll-theme-cayman
