title: Quantum Networking Resource List
description: Bruno Rijsman's lovingly hand-curated list of introductory books, papers, courses, and other online resources related to Quantum Networking, Quantum Communications, Quantum Key Distribution, and (to a lesser extent) Quantum Computing and Quantum Information Theory.
google_analytics: UA-31532124-6
theme: jekyll-theme-cayman
